version: '1.0'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

  api: 
    image: freitas-miranda/api-test:0.0.1
    networks:
      - k6     
    hostname: api-test
    ports:
      - "3131:3000"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M      
    
## Subir ambiente
# docker compose up -d influxdb grafana api

## Rodar os testes
# docker compose run k6 run /scripts/teste-carga.js
# docker compose run k6 run /scripts/teste-pico.js

## Dashboard
# http://localhost:3030/d/k6/k6-load-testing-results?orgId=1&refresh=5s 

## Resultados
#checks.........................:  43.59% ✓  936       ✗ 1211  15M
#checks.........................: 100.00% ✓ 4594       ✗ 0     50m
