services:
  influxdb:
    container_name: test-carga_influxdb
    image: influxdb:1.8
    networks:
      - localnet 
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: test-carga_grafana
    networks:
      - localnet 
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    container_name: test-carga_k6
    image: loadimpact/k6:latest
    networks:
      - localnet 
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts   

networks:
  localnet:
    name: localnet
    driver: bridge
    external: true           
    
# docker compose up -d influxdb grafana
